version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"   # Host machine ke port 8000 ko container ke port 8000 ke saath map karna
    volumes:
      - .:/var/www    # Project folder ko container ke andar mount karna
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7   # MySQL ka image use karenge
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"    # Host machine ke port 3306 ko container ke port 3306 ke saath map karna
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
