version: '3.8'

services:
  # Laravel PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage  # Ensure storage is correctly mapped
      - ./bootstrap/cache:/var/www/bootstrap/cache 
    ports:
      - "9000:9000"  # PHP-FPM
    networks:
      - ecommerce-network
    depends_on:
      - db
    env_file:
      - .env.docker
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # host:container
    networks:
      - ecommerce-network
    restart: unless-stopped

  # phpMyAdmin (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - ecommerce-network

  # NGINX Web Server
  nginx:
    image: nginx:latest
    container_name: ecommerce-nginx
    ports:
      - "8000:80"  # app URL: http://localhost:8000
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  db_data:
